# -- 主菜单 --
# 显示在页面顶部的导航栏

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "项目"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "关于我"
  pageRef = "about"
  weight = 30

# -- 底部菜单 --
# 显示在页面底部

[[footer]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "项目"
  pageRef = "projects"
  weight = 20

[[footer]]
  name = "关于我"
  pageRef = "about"
  weight = 30
